import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import client from "../config/shopify";
import Layout from "../components/Layout";
export default function Home({ products }) {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async (context) => {
  const products = await client.product.fetchAll();

  return {
    props: {
      products: JSON.parse(JSON.stringify(products)),
    },
  };
};
